### ISSUE TITLE
Add static resources for non-webservices users

### ISSUE THREAD

**Issue by jadrake75** [stamp-web/stamp-web-aurelia#1]
It will be useful for non-webservices users to have a way to access data without requiring webservices for read situations.  Using the static json file with a test-data=true query parameter would be helpful

**Comment by zhhz** [comment]
Any progress on this? Or any way I can connect to your webservices?

**Comment by jadrake75** [comment]
The files are included (for GET anyways).  They are in resources/data.  There may be a few missing (like stamps)..... since 99% of the calls are a GET to the collection, I wonder if just having an option in the gulp server to serve any request to /stamp-webservices/rest/countries - to stream the countries.json?

**Comment by jadrake75** [comment]
Closing since stamp-webservices can easily serve this purpose.
