### ISSUE TITLE
Files could be organized my module/domain instead of resource type (views, services, etc)

### ISSUE THREAD

**Issue by vcardins** [stamp-web/stamp-web-aurelia#55]
This isn't actually and issue, but a different point of view/approach. Directory structure guidelines https://scotch.io/tutorials/angularjs-best-practices-directory-structure. Something like: http://screencast.com/t/fFhn8uUiE.
Btw, this is the best aurelia repo I've seen so far, definitely I'll take a lot from it.

**Comment by jadrake75** [comment]
I guess in many respects it is very close to that guideline.  while there is not a 100% match of component/view to directory I have organized them around their functional area.  For example:

components/stamps

is for stamp editor related components. In this folder you will find the JS/HTML/LESS for the components. In this situation there is both stamp-table (a table listing - currently incomplete) and stamp-editor (the editor component - used nightly by me)

The views folder is not really views like you traditionally think of them in MVC apps.  It is really the "pages" whereas "components" are elements used by the pages.  But the views are more than just .html, and contain .less, .js and .html.  "services" in this regard are component/view independent singletons that are used throughout the app as a DAO for the REST backend.

I am open to ideas and changes, and am constantly evolving it.  I use the application nightly (and have used over 15 variants of it over the year).  Aurelia is simply the latest to replace the AnguarJS 1.X/Polymer-JS/Material version. 

I also use it as a testing ground for my "day" job which I collaborate on with a team of engineers building a large commercial application.
